// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProtos.proto

package com.jzs.user.dto;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserDTOOrBuilder extends
          // @@protoc_insertion_point(interface_extends:user.UserDTO)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional string mobile = 2;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 2;</code>
     */
    com.google.protobuf.ByteString
    getMobileBytes();

    /**
     * <code>optional string firstName = 3;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string firstName = 3;</code>
     */
    com.google.protobuf.ByteString
    getFirstNameBytes();

    /**
     * <code>optional string lastName = 4;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string lastName = 4;</code>
     */
    com.google.protobuf.ByteString
    getLastNameBytes();

    /**
     * <pre>
     * yyyy-MM-dd
     * </pre>
     *
     * <code>optional string birthDay = 6;</code>
     */
    java.lang.String getBirthDay();
    /**
     * <pre>
     * yyyy-MM-dd
     * </pre>
     *
     * <code>optional string birthDay = 6;</code>
     */
    com.google.protobuf.ByteString
    getBirthDayBytes();

    /**
     * <code>optional string sex = 7;</code>
     */
    java.lang.String getSex();
    /**
     * <code>optional string sex = 7;</code>
     */
    com.google.protobuf.ByteString
    getSexBytes();
  }
  /**
   * Protobuf type {@code user.UserDTO}
   */
  public  static final class UserDTO extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:user.UserDTO)
          UserDTOOrBuilder {
    // Use UserDTO.newBuilder() to construct.
    private UserDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserDTO() {
      uid_ = 0;
      mobile_ = "";
      firstName_ = "";
      lastName_ = "";
      birthDay_ = "";
      sex_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserDTO(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              birthDay_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return UserProtos.internal_static_user_UserDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return UserProtos.internal_static_user_UserDTO_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      UserProtos.UserDTO.class, UserProtos.UserDTO.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private volatile java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 2;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mobile = 2;</code>
     */
    public com.google.protobuf.ByteString
    getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object firstName_;
    /**
     * <code>optional string firstName = 3;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string firstName = 3;</code>
     */
    public com.google.protobuf.ByteString
    getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object lastName_;
    /**
     * <code>optional string lastName = 4;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string lastName = 4;</code>
     */
    public com.google.protobuf.ByteString
    getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 6;
    private volatile java.lang.Object birthDay_;
    /**
     * <pre>
     * yyyy-MM-dd
     * </pre>
     *
     * <code>optional string birthDay = 6;</code>
     */
    public java.lang.String getBirthDay() {
      java.lang.Object ref = birthDay_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthDay_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * yyyy-MM-dd
     * </pre>
     *
     * <code>optional string birthDay = 6;</code>
     */
    public com.google.protobuf.ByteString
    getBirthDayBytes() {
      java.lang.Object ref = birthDay_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        birthDay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 7;
    private volatile java.lang.Object sex_;
    /**
     * <code>optional string sex = 7;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sex = 7;</code>
     */
    public com.google.protobuf.ByteString
    getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mobile_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
      }
      if (!getBirthDayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, birthDay_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, uid_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mobile_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
      }
      if (!getBirthDayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, birthDay_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof UserProtos.UserDTO)) {
        return super.equals(obj);
      }
      UserProtos.UserDTO other = (UserProtos.UserDTO) obj;

      boolean result = true;
      result = result && (getUid()
              == other.getUid());
      result = result && getMobile()
              .equals(other.getMobile());
      result = result && getFirstName()
              .equals(other.getFirstName());
      result = result && getLastName()
              .equals(other.getLastName());
      result = result && getBirthDay()
              .equals(other.getBirthDay());
      result = result && getSex()
              .equals(other.getSex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDay().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserProtos.UserDTO parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProtos.UserDTO parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProtos.UserDTO parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProtos.UserDTO parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProtos.UserDTO parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static UserProtos.UserDTO parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProtos.UserDTO parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserProtos.UserDTO parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProtos.UserDTO parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static UserProtos.UserDTO parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserProtos.UserDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UserDTO}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:user.UserDTO)
            UserProtos.UserDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return UserProtos.internal_static_user_UserDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return UserProtos.internal_static_user_UserDTO_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserProtos.UserDTO.class, UserProtos.UserDTO.Builder.class);
      }

      // Construct using UserProtos.UserDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        mobile_ = "";

        firstName_ = "";

        lastName_ = "";

        birthDay_ = "";

        sex_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return UserProtos.internal_static_user_UserDTO_descriptor;
      }

      public UserProtos.UserDTO getDefaultInstanceForType() {
        return UserProtos.UserDTO.getDefaultInstance();
      }

      public UserProtos.UserDTO build() {
        UserProtos.UserDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserProtos.UserDTO buildPartial() {
        UserProtos.UserDTO result = new UserProtos.UserDTO(this);
        result.uid_ = uid_;
        result.mobile_ = mobile_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.birthDay_ = birthDay_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserProtos.UserDTO) {
          return mergeFrom((UserProtos.UserDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserProtos.UserDTO other) {
        if (other == UserProtos.UserDTO.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getBirthDay().isEmpty()) {
          birthDay_ = other.birthDay_;
          onChanged();
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        UserProtos.UserDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserProtos.UserDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {

        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 2;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public com.google.protobuf.ByteString
      getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder setMobile(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder clearMobile() {

        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder setMobileBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        mobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string firstName = 3;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string firstName = 3;</code>
       */
      public com.google.protobuf.ByteString
      getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string firstName = 3;</code>
       */
      public Builder setFirstName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string firstName = 3;</code>
       */
      public Builder clearFirstName() {

        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string firstName = 3;</code>
       */
      public Builder setFirstNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string lastName = 4;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastName = 4;</code>
       */
      public com.google.protobuf.ByteString
      getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastName = 4;</code>
       */
      public Builder setLastName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastName = 4;</code>
       */
      public Builder clearLastName() {

        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastName = 4;</code>
       */
      public Builder setLastNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthDay_ = "";
      /**
       * <pre>
       * yyyy-MM-dd
       * </pre>
       *
       * <code>optional string birthDay = 6;</code>
       */
      public java.lang.String getBirthDay() {
        java.lang.Object ref = birthDay_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthDay_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * yyyy-MM-dd
       * </pre>
       *
       * <code>optional string birthDay = 6;</code>
       */
      public com.google.protobuf.ByteString
      getBirthDayBytes() {
        java.lang.Object ref = birthDay_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          birthDay_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * yyyy-MM-dd
       * </pre>
       *
       * <code>optional string birthDay = 6;</code>
       */
      public Builder setBirthDay(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        birthDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * yyyy-MM-dd
       * </pre>
       *
       * <code>optional string birthDay = 6;</code>
       */
      public Builder clearBirthDay() {

        birthDay_ = getDefaultInstance().getBirthDay();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * yyyy-MM-dd
       * </pre>
       *
       * <code>optional string birthDay = 6;</code>
       */
      public Builder setBirthDayBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        birthDay_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>optional string sex = 7;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sex = 7;</code>
       */
      public com.google.protobuf.ByteString
      getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sex = 7;</code>
       */
      public Builder setSex(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 7;</code>
       */
      public Builder clearSex() {

        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 7;</code>
       */
      public Builder setSexBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        sex_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.UserDTO)
    }

    // @@protoc_insertion_point(class_scope:user.UserDTO)
    private static final UserProtos.UserDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserProtos.UserDTO();
    }

    public static UserProtos.UserDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserDTO>
            PARSER = new com.google.protobuf.AbstractParser<UserDTO>() {
      public UserDTO parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserDTO> getParserForType() {
      return PARSER;
    }

    public UserProtos.UserDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_user_UserDTO_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_user_UserDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\020UserProtos.proto\022\004user\"j\n\007UserDTO\022\013\n\003u" +
                    "id\030\001 \001(\005\022\016\n\006mobile\030\002 \001(\t\022\021\n\tfirstName\030\003 " +
                    "\001(\t\022\020\n\010lastName\030\004 \001(\t\022\020\n\010birthDay\030\006 \001(\t\022" +
                    "\013\n\003sex\030\007 \001(\tB\036\n\020com.jzs.user.dtoB\nUserPr" +
                    "otosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_user_UserDTO_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_user_UserDTO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_user_UserDTO_descriptor,
            new java.lang.String[] { "Uid", "Mobile", "FirstName", "LastName", "BirthDay", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
